name: Daily YTM map update

on:
  schedule:
    - cron: "10 4 * * *"   # каждый день 04:10 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -U pandas numpy requests

      - name: Ensure data folder
        run: mkdir -p data

      - name: Build JSON
        run: python build_ytm_json.py

      - name: Show result (debug)
        run: |
          ls -la data || true
          head -c 800 data/ytm_top20.json || true
          echo ""

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/ytm_top20.json
          git commit -m "Daily update ytm_top20.json" || exit 0
          git push
