name: Daily YTM map update

on:
  schedule:
    - cron: "10 4 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -U pandas numpy requests

      - name: Ensure folders
        run: mkdir -p data

      - name: Build JSON
        run: |
          python scripts/build_ytm_json.py
          echo "---- list data/ ----"
          ls -la data || true
          echo "---- head json ----"
          head -c 600 data/ytm_top20.json || true
          echo ""

      - name: Git status
        run: |
          git status
          git diff -- data/ytm_top20.json || true

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/ytm_top20.json
          git commit -m "Daily update ytm_top20.json" || exit 0
          git push
